Search.appendIndex(
    [
                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Exception\\SubstrateRequestException",
            "name": "SubstrateRequestException",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Exception-SubstrateRequestException.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Exception\\SubstrateRequestException\u003A\u003AerrorMessage\u0028\u0029",
            "name": "errorMessage",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Exception-SubstrateRequestException.html#method_errorMessage"
        },                {
            "fqsen": "\\ValueErrorException",
            "name": "ValueErrorException",
            "summary": "",
            "url": "classes/ValueErrorException.html"
        },                {
            "fqsen": "\\ValueErrorException\u003A\u003AerrorMessage\u0028\u0029",
            "name": "errorMessage",
            "summary": "",
            "url": "classes/ValueErrorException.html#method_errorMessage"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer",
            "name": "Signer",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer\u003A\u003Agenerate_mnemonic\u0028\u0029",
            "name": "generate_mnemonic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html#method_generate_mnemonic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer\u003A\u003Acreate_from_private_key\u0028\u0029",
            "name": "create_from_private_key",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html#method_create_from_private_key"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer\u003A\u003Acreate_from_mnemonic\u0028\u0029",
            "name": "create_from_mnemonic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html#method_create_from_mnemonic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer\u003A\u003Acreate_from_seed\u0028\u0029",
            "name": "create_from_seed",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html#method_create_from_seed"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring\\Signer\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Keyring-Signer.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Library\\ss58",
            "name": "ss58",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Library-ss58.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Library\\ss58\u003A\u003Ass58_decode\u0028\u0029",
            "name": "ss58_decode",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Library-ss58.html#method_ss58_decode"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Library\\ss58\u003A\u003Ass58_encode\u0028\u0029",
            "name": "ss58_encode",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Library-ss58.html#method_ss58_encode"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Author",
            "name": "Author",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Author.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Author\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Author.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Author\u003A\u003ApendingExtrinsics\u0028\u0029",
            "name": "pendingExtrinsics",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Author.html#method_pendingExtrinsics"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Author\u003A\u003AsubmitExtrinsic\u0028\u0029",
            "name": "submitExtrinsic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Author.html#method_submitExtrinsic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Author\u003A\u003AAUTHOR_PREFIX",
            "name": "AUTHOR_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Author.html#constant_AUTHOR_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Author\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Author.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Balances",
            "name": "Balances",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Balances.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Balances\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Balances.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Balances\u003A\u003Atransfer\u0028\u0029",
            "name": "transfer",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Balances.html#method_transfer"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Balances\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Balances.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain",
            "name": "Chain",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetBlock\u0028\u0029",
            "name": "getBlock",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getBlock"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003Aget_block\u0028\u0029",
            "name": "get_block",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_get_block"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003Aget_block_hash\u0028\u0029",
            "name": "get_block_hash",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_get_block_hash"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetBlockHash\u0028\u0029",
            "name": "getBlockHash",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getBlockHash"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetFinalisedHead\u0028\u0029",
            "name": "getFinalisedHead",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getFinalisedHead"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetFinalizedHead\u0028\u0029",
            "name": "getFinalizedHead",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getFinalizedHead"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetHead\u0028\u0029",
            "name": "getHead",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getHead"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getHeader"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AgetRuntimeVersion\u0028\u0029",
            "name": "getRuntimeVersion",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_getRuntimeVersion"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AsubscribeAllHeads\u0028\u0029",
            "name": "subscribeAllHeads",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_subscribeAllHeads"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AsubscribeFinalisedHeads\u0028\u0029",
            "name": "subscribeFinalisedHeads",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_subscribeFinalisedHeads"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AsubscribeFinalizedHeads\u0028\u0029",
            "name": "subscribeFinalizedHeads",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_subscribeFinalizedHeads"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AsubscribeNewHead\u0028\u0029",
            "name": "subscribeNewHead",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_subscribeNewHead"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003AsubscribeNewHeads\u0028\u0029",
            "name": "subscribeNewHeads",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#method_subscribeNewHeads"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003ACHAIN_PREFIX",
            "name": "CHAIN_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#constant_CHAIN_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Chain\u003A\u003A\u0024__get_block_handler",
            "name": "__get_block_handler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Chain.html#property___get_block_handler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Constants",
            "name": "Constants",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Constants.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Constants\u003A\u003ASTORAGE_HASH_SYSTEM_EVENTS",
            "name": "STORAGE_HASH_SYSTEM_EVENTS",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Constants.html#constant_STORAGE_HASH_SYSTEM_EVENTS"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Constants\u003A\u003ASTORAGE_HASH_SYSTEM_EVENTS_V9",
            "name": "STORAGE_HASH_SYSTEM_EVENTS_V9",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Constants.html#constant_STORAGE_HASH_SYSTEM_EVENTS_V9"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt",
            "name": "ExtrinsicReceipt",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aretrieve_extrinsic\u0028\u0029",
            "name": "retrieve_extrinsic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_retrieve_extrinsic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aextrinsic_idx\u0028\u0029",
            "name": "extrinsic_idx",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_extrinsic_idx"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aextrinsic\u0028\u0029",
            "name": "extrinsic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_extrinsic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Atriggered_events\u0028\u0029",
            "name": "triggered_events",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_triggered_events"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aprocess_events\u0028\u0029",
            "name": "process_events",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_process_events"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Ais_success\u0028\u0029",
            "name": "is_success",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_is_success"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aerror_message\u0028\u0029",
            "name": "error_message",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_error_message"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aweight\u0028\u0029",
            "name": "weight",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_weight"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Atotal_fee_amount\u0028\u0029",
            "name": "total_fee_amount",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_total_fee_amount"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003A__get_extrinsic_index\u0028\u0029",
            "name": "__get_extrinsic_index",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method___get_extrinsic_index"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003A__getitem__\u0028\u0029",
            "name": "__getitem__",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method___getitem__"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003A__iter__\u0028\u0029",
            "name": "__iter__",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method___iter__"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\ExtrinsicReceipt\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-ExtrinsicReceipt.html#method_get"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Grandpa",
            "name": "Grandpa",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Grandpa.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Grandpa\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Grandpa.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Grandpa\u003A\u003AroundState\u0028\u0029",
            "name": "roundState",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Grandpa.html#method_roundState"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Grandpa\u003A\u003AsubscribeJustifications\u0028\u0029",
            "name": "subscribeJustifications",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Grandpa.html#method_subscribeJustifications"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Grandpa\u003A\u003AGRANDPA_PREFIX",
            "name": "GRANDPA_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Grandpa.html#constant_GRANDPA_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Grandpa\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Grandpa.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair",
            "name": "Keypair",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_create"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Ainspect\u0028\u0029",
            "name": "inspect",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_inspect"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Asign\u0028\u0029",
            "name": "sign",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_sign"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_verify"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Agenerate_mnemonic\u0028\u0029",
            "name": "generate_mnemonic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_generate_mnemonic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Acreate_from_private_key\u0028\u0029",
            "name": "create_from_private_key",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_create_from_private_key"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Acreate_from_mnemonic\u0028\u0029",
            "name": "create_from_mnemonic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_create_from_mnemonic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003Acreate_from_seed\u0028\u0029",
            "name": "create_from_seed",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#method_create_from_seed"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003AKEYPAIR_PREFIX",
            "name": "KEYPAIR_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#constant_KEYPAIR_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Keypair\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Keypair.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\KeypairType",
            "name": "KeypairType",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-KeypairType.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\KeypairType\u003A\u003AED25519",
            "name": "ED25519",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-KeypairType.html#constant_ED25519"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\KeypairType\u003A\u003ASR25519",
            "name": "SR25519",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-KeypairType.html#constant_SR25519"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc",
            "name": "Rpc",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_system\u0028\u0029",
            "name": "get_system",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_system"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_state\u0028\u0029",
            "name": "get_state",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_state"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_author\u0028\u0029",
            "name": "get_author",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_author"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_chain\u0028\u0029",
            "name": "get_chain",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_chain"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_grandpa\u0028\u0029",
            "name": "get_grandpa",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_grandpa"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_keypair\u0028\u0029",
            "name": "get_keypair",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_keypair"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aget_runtime\u0028\u0029",
            "name": "get_runtime",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_get_runtime"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Amethods\u0028\u0029",
            "name": "methods",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_methods"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Asubscribe_newHead\u0028\u0029",
            "name": "subscribe_newHead",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_subscribe_newHead"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003Aunsubscribe_newHead\u0028\u0029",
            "name": "unsubscribe_newHead",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#method_unsubscribe_newHead"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003ARPC_PREFIX",
            "name": "RPC_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#constant_RPC_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003A\u0024system",
            "name": "system",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#property_system"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Rpc\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Rpc.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime",
            "name": "Runtime",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadata"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataModules\u0028\u0029",
            "name": "getMetadataModules",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataModules"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataCallFunctions\u0028\u0029",
            "name": "getMetadataCallFunctions",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataCallFunctions"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataStorageFunctions\u0028\u0029",
            "name": "getMetadataStorageFunctions",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataStorageFunctions"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataEvents\u0028\u0029",
            "name": "getMetadataEvents",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataEvents"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataEvent\u0028\u0029",
            "name": "getMetadataEvent",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataEvent"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataConstants\u0028\u0029",
            "name": "getMetadataConstants",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataConstants"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetTypeRegistry\u0028\u0029",
            "name": "getTypeRegistry",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getTypeRegistry"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getType"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetCustomTypes\u0028\u0029",
            "name": "getCustomTypes",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getCustomTypes"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AsetCustomTypes\u0028\u0029",
            "name": "setCustomTypes",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_setCustomTypes"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AaddCustomType\u0028\u0029",
            "name": "addCustomType",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_addCustomType"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AremoveCustomType\u0028\u0029",
            "name": "removeCustomType",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_removeCustomType"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AresetCustomTypes\u0028\u0029",
            "name": "resetCustomTypes",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_resetCustomTypes"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getState"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataErrors\u0028\u0029",
            "name": "getMetadataErrors",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataErrors"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AgetMetadataError\u0028\u0029",
            "name": "getMetadataError",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_getMetadataError"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AdecodeScale\u0028\u0029",
            "name": "decodeScale",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_decodeScale"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AencodeScale\u0028\u0029",
            "name": "encodeScale",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_encodeScale"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AcreateSignaturePayload\u0028\u0029",
            "name": "createSignaturePayload",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_createSignaturePayload"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003AsubmitExtrinsic\u0028\u0029",
            "name": "submitExtrinsic",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#method_submitExtrinsic"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003ARUNTIME_PREFIX",
            "name": "RUNTIME_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#constant_RUNTIME_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Runtime\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Runtime.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State",
            "name": "State",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003Acall\u0028\u0029",
            "name": "call",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_call"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_getMetadata"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AgetRuntimeVersion\u0028\u0029",
            "name": "getRuntimeVersion",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_getRuntimeVersion"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AsubscribeRuntimeVersion\u0028\u0029",
            "name": "subscribeRuntimeVersion",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_subscribeRuntimeVersion"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AsubscribeStorage\u0028\u0029",
            "name": "subscribeStorage",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_subscribeStorage"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AunsubscribeRuntimeVersion\u0028\u0029",
            "name": "unsubscribeRuntimeVersion",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_unsubscribeRuntimeVersion"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AunsubscribeStorage\u0028\u0029",
            "name": "unsubscribeStorage",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_unsubscribeStorage"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AgetStorage\u0028\u0029",
            "name": "getStorage",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_getStorage"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AgetStorageHash\u0028\u0029",
            "name": "getStorageHash",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_getStorageHash"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AgetStorageSize\u0028\u0029",
            "name": "getStorageSize",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_getStorageSize"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003AqueryStorage\u0028\u0029",
            "name": "queryStorage",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#method_queryStorage"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003ASTATE_PREFIX",
            "name": "STATE_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#constant_STATE_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\State\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-State.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System",
            "name": "System",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AaccountNextIndex\u0028\u0029",
            "name": "accountNextIndex",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_accountNextIndex"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003Achain\u0028\u0029",
            "name": "chain",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_chain"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AchainType\u0028\u0029",
            "name": "chainType",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_chainType"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003Ahealth\u0028\u0029",
            "name": "health",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_health"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AlocalListenAddresses\u0028\u0029",
            "name": "localListenAddresses",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_localListenAddresses"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AlocalPeerId\u0028\u0029",
            "name": "localPeerId",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_localPeerId"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_name"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AnodeRoles\u0028\u0029",
            "name": "nodeRoles",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_nodeRoles"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003Apeers\u0028\u0029",
            "name": "peers",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_peers"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003Aproperties\u0028\u0029",
            "name": "properties",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_properties"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AreservedPeers\u0028\u0029",
            "name": "reservedPeers",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_reservedPeers"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003AsyncState\u0028\u0029",
            "name": "syncState",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_syncState"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003Aversion\u0028\u0029",
            "name": "version",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#method_version"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003ASYSTEM_PREFIX",
            "name": "SYSTEM_PREFIX",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#constant_SYSTEM_PREFIX"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\System\u003A\u003A\u0024a",
            "name": "a",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-System.html#property_a"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction",
            "name": "Transaction",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction\u003A\u003Aget_balances\u0028\u0029",
            "name": "get_balances",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html#method_get_balances"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction\u003A\u003AsignAndSend\u0028\u0029",
            "name": "signAndSend",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html#method_signAndSend"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction\u003A\u003A\u0024apiHandler",
            "name": "apiHandler",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html#property_apiHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction\u003A\u003A\u0024destAddr",
            "name": "destAddr",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html#property_destAddr"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc\\Transaction\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-Rpc-Transaction.html#property_value"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface",
            "name": "SubstrateInterface",
            "summary": "base\u0020class\u0020to\u0020make\u0020endpoint\u0020call,\u0020encoding,\u0020decoding\nall\u0020basics\u0020to\u0020handle\u0020tokena\u0020and\u0020sign\u0020the\u0020request",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "class\u0020constructor",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#method___construct"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003AAPIHandler\u0028\u0029",
            "name": "APIHandler",
            "summary": "Function\u0020which\u0020call\u0020any\u0020API\u0020through\u0020CURL",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#method_APIHandler"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003Ass58_format\u0028\u0029",
            "name": "ss58_format",
            "summary": "ss58_format\u0020endpoint\u0020API",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#method_ss58_format"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A\u0024token_decimals",
            "name": "token_decimals",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#property_token_decimals"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A\u0024token_symbol",
            "name": "token_symbol",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#property_token_symbol"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003AsetSigner\u0028\u0029",
            "name": "setSigner",
            "summary": "Set\u0020Signer\u0020endpoint\u0020API",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#method_setSigner"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003Acompose_call\u0028\u0029",
            "name": "compose_call",
            "summary": "Compose\u0020Call\u0020API",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#method_compose_call"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003AAPI_URL",
            "name": "API_URL",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#constant_API_URL"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A\u0024rpc",
            "name": "rpc",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#property_rpc"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A\u0024tx",
            "name": "tx",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#property_tx"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A\u0024APIurl",
            "name": "APIurl",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#property_APIurl"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\SubstrateInterface\u003A\u003A\u0024httpMethod",
            "name": "httpMethod",
            "summary": "",
            "url": "classes/nitorInfoTechOss-SubstrateInterfacePackage-SubstrateInterface.html#property_httpMethod"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/nitorinfotechoss-substrateinterfacepackage-exception.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Keyring",
            "name": "Keyring",
            "summary": "",
            "url": "namespaces/nitorinfotechoss-substrateinterfacepackage-keyring.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Library",
            "name": "Library",
            "summary": "",
            "url": "namespaces/nitorinfotechoss-substrateinterfacepackage-library.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage\\Rpc",
            "name": "Rpc",
            "summary": "",
            "url": "namespaces/nitorinfotechoss-substrateinterfacepackage-rpc.html"
        },                {
            "fqsen": "\\nitorInfoTechOss\\SubstrateInterfacePackage",
            "name": "SubstrateInterfacePackage",
            "summary": "",
            "url": "namespaces/nitorinfotechoss-substrateinterfacepackage.html"
        },                {
            "fqsen": "\\nitorInfoTechOss",
            "name": "nitorInfoTechOss",
            "summary": "",
            "url": "namespaces/nitorinfotechoss.html"
        }            ]
);
